name: careve
description: A medical support app for women

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: 3.26.0
  flutter_localizations:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.0.0-nullsafety.11
  intl: ^0.17.0
  dots_indicator: ^2.0.0
  font_awesome_flutter: ^9.0.0
  flutter_image_compress: ^1.0.0
  dio: ^4.0.0-prev3
  pin_code_text_field: ^1.8.0
  smooth_star_rating: ^1.1.1
  flutter_staggered_animations: ^1.0.0
  hive_flutter: ^1.0.0-nullsafety.0
  avatar_glow: ^2.0.1
  youtube_player_flutter: ^8.0.0
  share: ^2.0.1
  polygon_clipper: ^1.0.2
  file_picker: ^3.0.1
  cached_network_image: ^3.0.0
  url_launcher: ^6.0.3
  geolocator: ^7.0.1
  google_maps_place_picker: ^2.0.0-nullsafety.3
  easy_debounce: ^2.0.0
  lottie: ^1.0.1
  bdaya_repository_pattern:
    git:
      url: git@github.com:Bdaya-Dev/Flutter-Repository-Pattern.git
      ref: master
  bdaya_custom_splash:
    git:
      url: https://github.com/Bdaya-Dev/custom-splash.git
      ref: master
  firebase_analytics: "^7.0.1"
  firebase_messaging: ^10.0.0
  flutter_launcher_icons: "^0.9.2"



dev_dependencies:
  build_runner: ^1.7.1
  flutter_test:
    sdk: flutter
  hive_generator: ^1.0.1


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/logo.png"
  remove_alpha_ios: true


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/lottie/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Black.ttf
        - asset: assets/fonts/Cairo-Bold.ttf
        - asset: assets/fonts/Cairo-ExtraLight.ttf
        - asset: assets/fonts/Cairo-Light.ttf
        - asset: assets/fonts/Cairo-SemiBold.ttf

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_intl:
  enabled: true
  main_locale: ar